### ISSUE TITLE
 Unexpected error while processing request: uninitialized constant Delayed

### ISSUE THREAD

**Issue by spidergears** [hirefire/hirefire#64]
Unexpected error while processing request: uninitialized constant Delayed

```
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/macro/delayed_job.rb:46:in `queue'
/app/config/initializers/hirefire.rb:3:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/middleware.rb:57:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/middleware.rb:57:in `block in dynos'
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/middleware.rb:56:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/middleware.rb:56:in `inject'
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/middleware.rb:56:in `dynos'
/app/vendor/bundle/ruby/2.1.0/gems/hirefire-resource-0.3.7/lib/hirefire/middleware.rb:45:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/response.rb:96:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:114:in `post_process'
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'
/app/vendor/bundle/ruby/2.1.0/gems/faye-websocket-0.7.2/lib/faye/adapters/thin.rb:40:in `process'
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'
/app/vendor/bundle/ruby/2.1.0/gems/faye-websocket-0.7.2/lib/faye/adapters/thin.rb:44:in `receive_data'
```

**Comment by spidergears** [comment]
Gem code around the error `/hirefire-resource-0.3.7/lib/hirefire/macro/delayed_job.rb `
```ruby
def queue(*queues)
          queues.flatten!

          if queues.last.is_a?(Hash)
            options = queues.pop
          else
            options = {}
          end

          case options[:mapper]
          when :active_record
            c = ::Delayed::Job
            c = c.where(:failed_at => nil)
            c = c.where("run_at <= ?", Time.now.utc)
            c = c.where("priority >= ?", options[:min_priority]) if options.key?(:min_priority)
            c = c.where("priority <= ?", options[:max_priority]) if options.key?(:max_priority)
            c = c.where(:queue => queues) unless queues.empty?
            c.count.tap { ActiveRecord::Base.clear_active_connections! }
          when :active_record_2
```
